# Generated by Django 3.2.4 on 2021-06-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_role_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='checked',
            new_name='defaultt',
        ),
    ]
