# Generated by Django 3.2.4 on 2021-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='idd',
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='foobarbaz'),
        ),
    ]
