# Generated by Django 3.2.4 on 2021-06-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='persianName',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
