# Generated by Django 3.2.4 on 2021-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210613_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(default='alaki', max_length=25),
            preserve_default=False,
        ),
    ]
