# Generated by Django 3.2.4 on 2021-06-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_checked_role_defaultt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='defaultt',
            new_name='default',
        ),
    ]
