# Generated by Django 3.2.4 on 2021-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_roles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
