# Generated by Django 3.2.4 on 2021-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='team',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black')], default='w', max_length=1),
        ),
    ]
