# Generated by Django 3.2.4 on 2021-06-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_roles_checked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
