# Generated by Django 3.2.4 on 2021-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_defaultt_role_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.BigIntegerField(default=0, unique=True, verbose_name='foobarbaz')),
                ('players', models.CharField(max_length=500, verbose_name='roles and numbers')),
            ],
        ),
    ]
