# Generated by Django 3.2.4 on 2021-06-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_role_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
