# Generated by Django 3.2.4 on 2021-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='persianName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
