# Generated by Django 3.2.4 on 2021-06-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_role_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='priority',
            new_name='order',
        ),
    ]
