# Generated by Django 3.2.4 on 2021-06-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_poll_polloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='foo',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
